function g = jacobiansparse(auxdata)
N = cell2mat(auxdata(1));
I = speye(N);
Zero = sparse(N,N);
Psi = sparse(tril(ones(N), -1));
g = [Zero I I I I I; ...
    Zero Zero Zero Psi I Zero; ...
    I Zero Psi Zero Zero Zero; ...
    I I Zero Zero Zero Zero; ...
    Zero I I Zero Zero I; ...
    Zero I I Zero Zero I; ...
    I Zero Zero Zero Zero I; ...
    Zero I I Zero Zero I;];
end